-- CREATE SEQUENCES FOR EMPLOYEE AND DEPARTMENT TABLES
CREATE SEQUENCE IF NOT EXISTS SEQ_EMPLOYEE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_DEPARTMENT START WITH 1 INCREMENT BY 1;

-- EMPLOYEE TABLE
CREATE TABLE EMPLOYEE
(
    ID         BIGINT PRIMARY KEY,
    NAME_FIRST VARCHAR(100) NOT NULL,
    NAME_LAST  VARCHAR(100) NOT NULL
);

-- DEPARTMENT TABLE
CREATE TABLE DEPARTMENT
(
    ID        BIGINT PRIMARY KEY,
    NAME      VARCHAR(100) NOT NULL UNIQUE,
    READ_ONLY TINYINT DEFAULT 0,
    MANDATORY TINYINT DEFAULT 0
);

-- MAPPING TABLE FOR EMPLOYEE-DEPARTMENT RELATIONSHIP (MANY-TO-MANY)
CREATE TABLE MAP_EMPLOYEE_DEPARTMENT
(
    ID_EMPLOYEE   BIGINT NOT NULL,
    ID_DEPARTMENT BIGINT NOT NULL,
    PRIMARY KEY (ID_EMPLOYEE, ID_DEPARTMENT),
    FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE (ID),
    FOREIGN KEY (ID_DEPARTMENT) REFERENCES DEPARTMENT (ID)
);
